# Generated by Django 4.1.3 on 2023-06-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=36, unique=True)),
                ('user_info', models.JSONField(default=dict)),
                ('email', models.TextField()),
                ('location_raise', models.TextField()),
                ('email_input', models.TextField()),
                ('location_raise_input', models.TextField()),
                ('title', models.TextField()),
                ('remarks', models.TextField()),
                ('hash_tags', models.TextField()),
                ('resolve_state', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Ticket Log',
                'verbose_name_plural': 'Ticket Log',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TicketLogAttachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='ticket')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.ticketlog')),
            ],
            options={
                'verbose_name': 'Attachments of Ticket',
                'verbose_name_plural': 'Attachments of Ticket',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
