# Generated by Django 4.1.3 on 2024-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlogattachments',
            name='img',
            field=models.ImageField(upload_to='ticket'),
        ),
    ]
