# Generated by Django 4.1.3 on 2024-11-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_ticketlogattachments_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='resolve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='resolve_msg',
            field=models.TextField(blank=True),
        ),
    ]
