# Generated by Django 4.1.3 on 2022-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
