# Generated by Django 4.1.3 on 2023-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies_data',
            field=models.JSONField(default=list, help_text='[{...company detail...},]'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_current_data',
            field=models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_current_data',
            field=models.JSONField(default=dict, help_text='{"id": "", "first_name": "", "last_name": "", "email": "", "phone": ""}'),
        ),
        migrations.AddField(
            model_name='user',
            name='space_current_data',
            field=models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_current_data',
            field=models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}'),
        ),
    ]
