# Generated by Django 4.1.3 on 2023-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_companies_data_user_company_current_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_space_selected',
            field=models.CharField(default=None, help_text='Space code of user', max_length=100),
        ),
    ]
