# Generated by Django 4.1.3 on 2024-09-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_tenant_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tenant'),
        ),
    ]
