"""
Django settings for misui project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p8r4sbt&9q*ig^3_$ao95)n3)vq5hu40k8d4jqep8zzpt49sx1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = \
    [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ] + [
        'compressor',
        'apps.sharedapp',
    ] + [  # Core Application
        'apps.core.account',
        'apps.core.auths',
        'apps.core.home',
        'apps.core.hr',
        'apps.core.company',
        'apps.core.base',
        'apps.core.workflow',
    ] + [  # Another Application
        'apps.sale.saledata',
        'apps.sale.promotion',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.auths.middleware.CustomMiddleware',
]
MIDDLEWARE += ['apps.shared.middleware.JaegerTracingMiddleware']

ROOT_URLCONF = 'misui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'misui.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGE_CODE = 'en'

LANGUAGE_CHOICE = (
    ('en', 'English'),
    ('vi', 'Vietnamese'),
)

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'statics'),)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST API
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
    'PAGE_SIZE': 100,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

AUTH_USER_MODEL = 'account.User'

SESSION_COOKIE_AGE = 7 * 24 * 60 * 60  # 3 days expires

# call API Config
API_IP_OR_ADDR = '127.0.0.1'
API_PORT = '8000'  # None is remove port from url
API_USE_SSL = False
API_URL_PREFIX = 'api'

# parsing
protocol = "https" if API_USE_SSL else "http"
domain = f'{API_IP_OR_ADDR}{f":{API_PORT}" if API_PORT else ""}'
prefix = f"{API_URL_PREFIX}/" if API_URL_PREFIX else ""
API_DOMAIN = None

# Key return resp after call API
API_KEY_AUTH = 'Authorization'
API_PREFIX_TOKEN = 'Bearer'
API_KEY_RESPONSE_DATA = 'result'
API_KEY_RESPONSE_ERRORS = 'errors'
API_KEY_RESPONSE_STATUS = 'status'
API_KEY_RESPONSE_PAGE_SIZE = 'page_size'
API_KEY_RESPONSE_PAGE_COUNT = 'count'
API_KEY_RESPONSE_PAGE_NEXT = 'next'
API_KEY_RESPONSE_PAGE_PREVIOUS = 'previous'
API_KEY_MINIMAL = 'DATAISMINIMAL'
API_KEY_VALUE_MINIMAL = 'SuaD2m '

UI_RESP_KEY_STATE = 'state'
UI_RESP_KEY_STATUS = 'status'
UI_RESP_KEY_RESULT = 'result'
UI_RESP_KEY_ERRORS = 'errors'
UI_RESP_KEY_PAGE_SIZE = 'page_size'
UI_RESP_KEY_PAGE_COUNT = 'page_count'
UI_RESP_KEY_PAGE_NEXT = 'page_next'
UI_RESP_KEY_PAGE_PREVIOUS = 'page_previous'

# DEBUG CODE enable: allow raise errors if it is enabled else return default value (value is correct type)
RAISE_EXCEPTION_DEBUG = True

# LOGGING

LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%d/%b/%Y-%H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "api.log"),
            "when": "D",
            "interval": 1,
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["file"],
            "level": "INFO",
        },
    },
}

# memcache
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
#         'LOCATION': '127.0.0.1:11211',
#         'OPTIONS': {
#             'no_delay': True,
#             'ignore_exc': True,
#             'max_pool_size': 4,
#             'use_pooling': True,
#         }
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# LOGIN
LOGIN_URL = 'auth/login'

# option database
USE_DATABASE_CONFIG_OPTION = 0  # choices: 0=None,1=dev,2=online_site

# Tracing
JAEGER_TRACING_HOST = os.environ.get('JAEGER_TRACING_HOST', '127.0.0.1')
JAEGER_TRACING_PORT = os.environ.get('JAEGER_TRACING_PORT', 6831)
JAEGER_TRACING_PROJECT_NAME = os.environ.get('JAEGER_TRACING_PROJECT_NAME', 'MiS UI')
JAEGER_TRACING_ENABLE = os.environ.get('JAEGER_TRACING_ENABLE', False)
JAEGER_TRACING_ENABLE = True if JAEGER_TRACING_ENABLE in ['True', 'true', '1'] else False
JAEGER_TRACING_EXCLUDE_LOG_PATH = '/__'

# another import

try:
    from .local_settings import *
except ImportError:
    pass

# Replace API DOMAIN
if not API_DOMAIN:
    API_DOMAIN = f'{protocol}://{domain}/{prefix}'

# Database configurations
if not DATABASES or (isinstance(DATABASES, dict) and 'default' not in DATABASES):
    match USE_DATABASE_CONFIG_OPTION:
        case 1:
            DATABASES.update(
                {
                    'default': {
                        'ENGINE': 'django.db.backends.mysql',
                        'NAME': 'my_db_ui',
                        'USER': 'my_user',
                        'PASSWORD': 'my_password',
                        'HOST': '127.0.0.1',
                        'PORT': '3307',
                    }
                }
            )
        case 2:
            DATABASES.update(
                {
                    'default': {
                        'ENGINE': 'django.db.backends.mysql',
                        'NAME': os.environ.get('DB_NAME'),
                        'USER': os.environ.get('DB_USER'),
                        'PASSWORD': os.environ.get('DB_PASSWORD'),
                        'HOST': os.environ.get('DB_HOST'),
                        'PORT': os.environ.get('DB_PORT'),
                    }
                }
            )
            API_DOMAIN_ENV = os.environ.get('API_DOMAIN')
            if API_DOMAIN_ENV:
                API_DOMAIN = f'{API_DOMAIN_ENV}/{prefix}'
        case _:
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }

if DEBUG is True:
    from colorama import Fore

    db_option = 'DOCKER-DEV' if USE_DATABASE_CONFIG_OPTION == 1 else 'DOCKER-PROD' if USE_DATABASE_CONFIG_OPTION == 2 else 'DB SERVICE'
    print(Fore.CYAN, '### SETTINGS CONFIG VERBOSE ----------------------------------------------------#', '\033[0m')
    match USE_DATABASE_CONFIG_OPTION:
        case 1:
            print(Fore.BLUE, '#  1. DATABASES:          [DOCKER-DEV]:          ', DATABASES, '\033[0m')
        case 2:
            print(Fore.BLUE, '#  1. DATABASES:          [DOCKER-PROD]:         ', DATABASES, '\033[0m')
        case _:
            print(Fore.BLUE, '#  1. DATABASES:          [LOCAL]:               ', DATABASES, '\033[0m')
    print(Fore.YELLOW, '#  2. API_DOMAIN:                                ', API_DOMAIN, '\033[0m')
    if JAEGER_TRACING_ENABLE is True:
        print(
            Fore.LIGHTBLUE_EX,
            '#  3. TRACING [JAEGER]:                          ',
            f"{JAEGER_TRACING_HOST}:{JAEGER_TRACING_PORT} / {JAEGER_TRACING_PROJECT_NAME} \033[0m",
        )
    else:
        print(Fore.LIGHTBLUE_EX, '#  3. TRACING [JAEGER]:                           Disable \033[0m')
    print(Fore.CYAN, '----------------------------------------------------------------------------------', '\033[0m')
