"""
Django settings for misui project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import json
import os
from colorama import Fore
from pathlib import Path

from .load_env import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load environment from .env file
load_env(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p8r4sbt&9q*ig^3_$ao95)n3)vq5hu40k8d4jqep8zzpt49sx1'

GG_RECAPTCHA_ENABLED = True if os.environ.get('GG_RECAPTCHA_ENABLED', '0') in [1, '1'] else False
GG_RECAPTCHA_SERVER_KEY = os.environ.get('GG_RECAPTCHA_SERVER_KEY', '6LfNp8YnAAAAAH2nG-MQfa__3p71shh10CE8KfLX')
GG_RECAPTCHA_CLIENT_KEY = os.environ.get('GG_RECAPTCHA_CLIENT_KEY', '6LfNp8YnAAAAAE9qAY7kCFcRFOigzLQjqlyQIcnM')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEBUG_JS = True
DEBUG_NOTIFY_KEY = True
ALLOWED_HOSTS = []

# Google Analytics
GA_COLLECTION_ENABLED = True if os.environ.get('GA_COLLECTION_ENABLED', '0') in [1, '1'] else False
GA_SCRIPT = os.environ.get('GA_SCRIPT', '')
GA_CODE = os.environ.get('GA_CODE', '')

IS_SERVER_MAINTAINING = True if os.environ.get('IS_SERVER_MAINTAINING', '0') in [1, '1'] else False

RELEASE_VERSION = os.environ.get('RELEASE_VERSION', '0.0.1')

CSRF_TRUSTED_ORIGINS = json.loads(os.environ.get('CSRF_TRUSTED_ORIGINS', '[]'))

# Application definition

INSTALLED_APPS = \
    [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ] + [
        'compressor',
        'apps.sharedapp',
        'apps.log',
        'django_celery_results',  # Listen celery task and record it to database.
        'apps.core.chatbot',  # bflow-ai AI
        'django_celery_beat',  # celery crontab
        'apps.core.chat3rd',  # Chat Third party: Messenger, Zalo, WhatsApp
        'apps.core.firebase',  # Firebase
    ] + [  # Core Application
        'apps.core.account',
        'apps.core.auths',
        'apps.core.home',
        'apps.core.hr',
        'apps.core.tenant',
        'apps.core.company',
        'apps.core.base',
        'apps.core.workflow',
        'apps.core.process',
        'apps.core.programme',
        'apps.core.comment',
        'apps.core.printer',
        'apps.core.mailer',
        'apps.core.fimport',
        'apps.core.diagram',
        'apps.core.attachment',
        'apps.core.form',
        'apps.core.recurrence',
        'apps.core.contract_template',
    ] + [  # Another Application
        'apps.masterdata.saledata',
        'apps.masterdata.promotion',
    ] + [  # Sales Application
        'apps.sales.opportunity',
        'apps.sales.quotation',
        'apps.sales.saleorder',
        'apps.sales.cashoutflow',
        'apps.sales.delivery',
        'apps.sales.task',
        'apps.sales.purchasing',
        'apps.sales.inventory',
        'apps.sales.report',
        'apps.sales.acceptance',
        'apps.sales.dashboard',
        'apps.sales.revenueplan',
        'apps.sales.arinvoice',
        'apps.sales.apinvoice',
        'apps.sales.lead',
        'apps.sales.project',
        'apps.sales.budgetplan',
        'apps.sales.contract',
        'apps.sales.distributionplan',
        'apps.sales.production',
        'apps.sales.bidding',
        'apps.sales.leaseorder',
        'apps.sales.consulting',
        'apps.sales.partnercenter',
        'apps.sales.grouporder',
        'apps.sales.productmodification',
        'apps.sales.productmodificationbom',
        'apps.sales.equipmentloan',
        'apps.sales.equipmentreturn',
        'apps.sales.serviceorder',
        'apps.sales.servicequotation',
    ] + [  # e-office Application
        'apps.eoffice.leave',
        'apps.eoffice.businesstrip',
        'apps.eoffice.assettools',
        'apps.eoffice.meeting',
    ] + [  # external
        'apps.web_builder',
    ] + [  # HRM
        'apps.hrm.employee',
        'apps.hrm.attendance',
        'apps.hrm.absenceexplanation',
        'apps.hrm.overtimerequest',
        'apps.hrm.payroll',
    ] + [
        'apps.sales.financialcashflow',
        'apps.sales.reconciliation',
        'apps.sales.asset',
        'apps.sales.paymentplan',
    ] + [
        'apps.accounting.accountingsettings',
        'apps.accounting.journalentry',
        'apps.accounting.budget',
        'apps.accounting.accountingreport',
    ] + [
        'apps.kms.document_approval',
        'apps.kms.incomingdocument',
    ]

INSTALLED_APPS += [
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.auths.middleware.CustomMiddleware',
]

ROOT_URLCONF = 'misui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'misui.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = ['apps.core.auths.authentication.MyAuthenticate']

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGE_CODE = 'en'

LANGUAGE_CHOICE = (
    ('en', 'English'),
    ('vi', 'Vietnamese'),
)

LANGUAGE_CHOICE_CODE = [item[0] for item in LANGUAGE_CHOICE]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'statics'),)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

default_auto_field = 'django.db.models.BigAutoField'

# REST API
JWT_KEY_2FA_ENABLED = 'is_2fa_enabled'
JWT_KEY_2FA_VERIFIED = 'is_2fa_verified'
REST_FRAMEWORK = {
    'DEFAULT_METADATA_CLASS': None,
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        # 'apps.shared.drf.IsAuthenticatedDisableOptionsPermission',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
    'PAGE_SIZE': 100,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}
if DEBUG is True:
    REST_FRAMEWORK['DEFAULT_METADATA_CLASS'] = 'rest_framework.metadata.SimpleMetadata'
AUTH_USER_MODEL = 'account.User'

SESSION_COOKIE_AGE = 1 * 24 * 60 * 60  # 3 days expires

# CELERY + RABBITMQ CONFIG
CELERY_BROKER_URL = None  # 'amqp://guest:guest@127.0.0.1:5672//'
CELERY_TASK_ALWAYS_EAGER = True  # allow executable task real-time (True) or push task to queue (False)
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'

# CELERY BEAT
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
DJANGO_CELERY_BEAT_TZ_AWARE = False

if os.environ.get('CELERY_ENABLED', '0') in [1, '1']:
    CELERY_TASK_ALWAYS_EAGER = True if os.environ.get('CELERY_TASK_ALWAYS_EAGER', 0) in [1, '1'] else False

    CELERY_BROKER_VHOST = os.environ.get('MSG_QUEUE_BROKER_VHOST', '/')
    MSG_QUEUE_HOST = os.environ.get("MSG_QUEUE_HOST")  # '127.0.0.1' or host_name
    MSG_QUEUE_PORT = os.environ.get("MSG_QUEUE_PORT")  # default '5672'
    MSG_QUEUE_USER = os.environ.get("MSG_QUEUE_USER")  # default 'rabbitmq_user'
    MSG_QUEUE_PASSWORD = os.environ.get("MSG_QUEUE_PASSWORD")  # default 'rabbitmq_password'
    if MSG_QUEUE_HOST and MSG_QUEUE_PORT:
        CELERY_BROKER_URL = f'amqp://{MSG_QUEUE_USER}:{MSG_QUEUE_PASSWORD}@{MSG_QUEUE_HOST}:{MSG_QUEUE_PORT}'
    else:
        raise ValueError('CELERY CONFIG must be required HOST & PORT.')

# -- CELERY + RABBITMQ CONFIG


# call API Config
API_IP_OR_ADDR = '127.0.0.1'
API_PORT = '8000'  # None is remove port from url
API_USE_SSL = False
API_URL_PREFIX = 'api'

# parsing
protocol = "https" if API_USE_SSL else "http"
domain = f'{API_IP_OR_ADDR}{f":{API_PORT}" if API_PORT else ""}'
prefix = f"{API_URL_PREFIX}/" if API_URL_PREFIX else ""
API_DOMAIN_SIMPLE = f'{protocol}://{domain}'
API_DOMAIN = f'{protocol}://{domain}/{prefix}'

# main UI domain
UI_PROTOCOL = os.environ.get('UI_PROTOCOL', 'http')
UI_DOMAIN = os.environ.get('UI_DOMAIN', '127.0.0.1')
UI_DOMAIN_SUB_DOMAIN = '.' + UI_DOMAIN
UI_DOMAIN_SUB_HOME = os.environ.get('UI_DOMAIN_SUB_HOME', 'home')
UI_FULL_DOMAIN = os.environ.get('UI_FULL_DOMAIN', 'http://{sub_domain}.local.test:8001')
UI_FIXED_DOMAIN = os.environ.get('UI_FIXED_DOMAIN', None)
UI_URL = os.environ.get('UI_URL') if os.environ.get('UI_URL', None) else f'{UI_PROTOCOL}://{UI_DOMAIN}'
UI_ALLOW_AUTO_TENANT = True if os.environ.get('UI_ALLOW_AUTO_TENANT', '0') in [1, '1'] else False
UI_SUB_ALLOWED = json.loads(os.environ.get('UI_SUB_ALLOWED', '["*"]'))
UI_SUB_DENIED = json.loads(os.environ.get('UI_SUB_DENIED', '[]'))
UI_ALLOW_SHOW_SELECT_TENANT = True if os.environ.get('UI_ALLOW_SHOW_SELECT_TENANT', '1') in [1, '1'] else False

# Media key and data private
MEDIA_KEY_FLAG = os.environ.get('MEDIA_KEY_FLAG', 'MEDIA-APIRequest')
MEDIA_KEY_SECRET_TOKEN_UI = os.environ.get('MEDIA_KEY_SECRET_TOKEN_UI', 'UI-SECRET-KEY-APIRequest')
MEDIA_SECRET_TOKEN_UI = os.environ.get('MEDIA_SECRET_TOKEN_UI', 'Yk4pfMCqAgzZK3cO')
# media server
MEDIA_DOMAIN = os.environ.get('MEDIA_DOMAIN', 'http://127.0.0.1:8881/api/')
MEDIA_PUBLIC_DOMAIN = os.environ.get('MEDIA_PUBLIC_DOMAIN', MEDIA_DOMAIN)
MEDIA_TIMEOUT = int(os.environ.get('MEDIA_TIMEOUT', '0'))  # seconds
# Key return resp after call API
API_KEY_AUTH = 'Authorization'
API_PREFIX_TOKEN = 'Bearer'
API_KEY_AUTH_REFRESH = 'Authorization_Refresh'
API_KEY_RESPONSE_DATA = 'result'
API_KEY_RESPONSE_ERRORS = 'errors'
API_KEY_RESPONSE_STATUS = 'status'
API_KEY_RESPONSE_PAGE_SIZE = 'page_size'
API_KEY_RESPONSE_PAGE_COUNT = 'count'
API_KEY_RESPONSE_PAGE_NEXT = 'next'
API_KEY_RESPONSE_PAGE_PREVIOUS = 'previous'
API_KEY_MINIMAL = 'DATAISMINIMAL'
API_KEY_VALUE_MINIMAL = 'SuaD2m '

UI_RESP_KEY_STATE = 'state'
UI_RESP_KEY_STATUS = 'status'
UI_RESP_KEY_RESULT = 'result'
UI_RESP_KEY_ERRORS = 'errors'
UI_RESP_KEY_PAGE_SIZE = 'page_size'
UI_RESP_KEY_PAGE_COUNT = 'page_count'
UI_RESP_KEY_PAGE_NEXT = 'page_next'
UI_RESP_KEY_PAGE_PREVIOUS = 'page_previous'

# DEBUG CODE enable: allow raise errors if it is enabled else return default value (value is correct type)
RAISE_EXCEPTION_DEBUG = True

# memcache
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
#         'LOCATION': '127.0.0.1:11211',
#         'OPTIONS': {
#             'no_delay': True,
#             'ignore_exc': True,
#             'max_pool_size': 4,
#             'use_pooling': True,
#         }
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# another import

try:
    from .local_settings import *
except ImportError:
    pass

# Logging
if os.environ.get('ENABLE_LOGGING', False) in [1, '1']:
    LOG_DIR = os.path.join(BASE_DIR, "logs")
    if not os.path.exists(LOG_DIR):
        os.makedirs(LOG_DIR)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%d/%b/%Y-%H:%M:%S",
            },
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "ui.log"),
                "when": "D",
                "interval": 1,
                "backupCount": 10,
                "formatter": "verbose",
            },
        },
        "loggers": {
            "": {
                "handlers": ["file"],
                "level": "INFO",
            },
        },
    }
# -- Logging

# Tracing
JAEGER_TRACING_ENABLE = os.environ.get('ENABLE_TRACING', False) in [1, '1']
if JAEGER_TRACING_ENABLE is True:
    JAEGER_TRACING_HOST = os.environ.get('JAEGER_TRACING_HOST', 'jaeger_global')
    JAEGER_TRACING_PORT = os.environ.get('JAEGER_TRACING_PORT', 6831)
    JAEGER_TRACING_PROJECT_NAME = os.environ.get('JAEGER_TRACING_PROJECT_NAME', 'MiS UI')
    JAEGER_TRACING_EXCLUDE_LOG_PATH = '/__'
# -- Tracing

# PROD configurations
if os.environ.get('ENABLE_PROD', '0') in [1, '1']:
    # allow host
    OS_ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '[]')
    ALLOWED_HOSTS = json.loads(OS_ALLOWED_HOSTS)

    # allow csrf for ssl
    OS_CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '[]')
    CSRF_TRUSTED_ORIGINS = json.loads(OS_CSRF_TRUSTED_ORIGINS)

    # setup database default
    DATABASES.update(
        {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.environ.get('DB_NAME'),
                'USER': os.environ.get('DB_USER'),
                'PASSWORD': os.environ.get('DB_PASSWORD'),
                'HOST': os.environ.get('DB_HOST'),
                'PORT': os.environ.get('DB_PORT'),
            }
        }
    )
    # Replace API DOMAIN
    API_DOMAIN = os.environ.get('API_DOMAIN', None)
    API_DOMAIN_SIMPLE = os.environ.get('API_DOMAIN_SIMPLE', API_DOMAIN.replace("/api/", ""))

    # SECURITY : https://docs.djangoproject.com/en/5.1/ref/settings/#secure-proxy-ssl-header
    USE_PROXY_FORWARD = os.environ.get('USE_PROXY_FORWARD', '')
    if USE_PROXY_FORWARD in ['http', 'https']:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', USE_PROXY_FORWARD)

#
USE_S3 = os.getenv('USE_S3', '0') == '1'

# compressor config
# COMPRESS_OFFLINE = False
# COMPRESS_ROOT_PARENT = os.path.join(STATIC_ROOT, 'compressor')
# COMPRESS_ROOT = os.path.join(COMPRESS_ROOT_PARENT, RELEASE_VERSION)
if os.environ.get('COMPRESS_ENABLED', '0') in [1, '1']:
    COMPRESS_ENABLED = True
else:
    COMPRESS_ENABLED = False
# -- compressor config

# -- PROD configurations

OS_DEBUG = os.environ.get('DEBUG', DEBUG)
if OS_DEBUG is True or OS_DEBUG in [1, '1']:
    DEBUG = True
    print(Fore.CYAN, '### SETTINGS CONFIG VERBOSE ----------------------------------------------------#', '\033[0m')
    print(Fore.BLUE, f'#  1. DATABASES: {str(DATABASES)} \033[0m')
    print(Fore.YELLOW, f'#  2. API_DOMAIN: {str(API_DOMAIN)} \033[0m')
    print(Fore.LIGHTBLUE_EX, f'#  3. TRACING [JAEGER]: {JAEGER_TRACING_ENABLE}')
    print(Fore.GREEN, f'#  4. COMPRESSOR ENABLE: {COMPRESS_ENABLED}')
    print(Fore.LIGHTGREEN_EX, f'#  5. GA ENABLE: {GA_COLLECTION_ENABLED}')
    print(Fore.CYAN, '----------------------------------------------------------------------------------', '\033[0m')
else:
    DEBUG = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


# -- FILE SIZES SETUP
FILE_SIZE_COMPANY_LOGO = int(
    os.getenv('FILE_SIZE_COMPANY_LOGO', 1024 * 1024 * 3)  # 3MB
)
FILE_SIZE_COMPANY_ICON = int(
    os.getenv('FILE_SIZE_COMPANY_ICON', 1024 * 100)  # 100KB
)
FILE_SIZE_WEB_BUILDER = int(
    os.getenv('FILE_SIZE_UPLOAD_LIMIT', 5 * 1024 * 1024)  # 5MB
)
FILE_AVATAR_MAX_SIZE = 3 * 1024 * 1024  # 3MiB
FILE_SIZE_UPLOAD_LIMIT = int(
    os.getenv('FILE_SIZE_UPLOAD_LIMIT', 20 * 1024 * 1024)  # 20MB
)
