"""system module"""
from django.utils.translation import gettext_lazy as _


class SaleMsg:  # pylint: disable=too-few-public-methods
    """Sale's applications message translation"""
    OPPORTUNITY_CREATE = _('Opportunity create successfully')
    OPPORTUNITY_UPDATE = _('Opportunity update successfully')
    QUOTATION_CREATE = _('Quotation create successfully')
    QUOTATION_UPDATE = _('Quotation update successfully')
    SALE_ORDER_CREATE = _('Sale order create successfully')
    SALE_ORDER_UPDATE = _('Sale order update successfully')
    QUOTATION_CONFIG_UPDATE = _('Quotation config update successfully')
    SALE_ORDER_CONFIG_UPDATE = _('Sale order config update successfully')
    OPPORTUNITY_CONFIG_UPDATE = _('Opportunity config update successfully')
    ADVANCE_PAYMENT_CREATE = _('Advance payment create successfully')
    ADVANCE_PAYMENT_UPDATE = _('Advance payment update successfully')
    PAYMENT_CREATE = _('Payment create successfully')
    PAYMENT_UPDATE = _('Payment update successfully')
    QUOTATION_INDICATOR_CREATE = _('Quotation indicator create successfully')
    QUOTATION_INDICATOR_UPDATE = _('Quotation indicator update successfully')
    QUOTATION_INDICATOR_RESTORE = _('Quotation indicator restore successfully')
    OPPORTUNITY_CALL_LOG_CREATE = _('Opportunity Call Log create successfully')
    OPPORTUNITY_EMAIL_SEND = _('Opportunity Email send successfully')
    OPPORTUNITY_MEETING_CREATED = _('Opportunity Meeting create successfully')
    SALE_ORDER_INDICATOR_CREATE = _('Sale order indicator create successfully')
    SALE_ORDER_INDICATOR_UPDATE = _('Sale order indicator update successfully')
    SALE_ORDER_INDICATOR_RESTORE = _('Sale order indicator restore successfully')
    OPPORTUNITY_TASK_CONFIG_UPDATE = _('Opportunity task config update successfully')
    OPPORTUNITY_TASK_CREATE = _('Task create successfully')
    OPPORTUNITY_TASK_UPDATE = _('Task update successfully')
    OPPORTUNITY_TASK_DELETE = _('Task delete successfully')
    OPPORTUNITY_TASK_LOG = _('Log time successfully')
    PURCHASE_ORDER_CREATE = _('Purchase order create successfully')
    PURCHASE_ORDER_UPDATE = _('Purchase order update successfully')
    PURCHASE_QUOTATION_REQUEST = _('Purchase Quotation Request create successfully')
