from .bidding_bidding import BIDDING_DATA_MAP
from .cashoutflow_advance import ADVANCE_DATA_MAP
from .cashoutfow_payment import PAYMENT_DATA_MAP
from .cashoutflow_return_advance import RETURN_ADVANCE_DATA_MAP
from .consulting_consulting import CONSULTING_DATA_MAP
from .delivery_order_delivery import DELIVERY_DATA_MAP
from .inventory_goods_receipt import GOODS_RECEIPT_DATA_MAP
from .inventory_goods_issue import GOODS_ISSUE_DATA_MAP
from .inventory_goods_transfer import GOODS_TRANSFER_DATA_MAP
from .inventory_goods_return import GOODS_RETURN_DATA_MAP
from .purchasing_purchase_order import PURCHASE_ORDER_DATA_MAP
from .purchasing_purchase_request import PURCHASE_REQUEST_DATA_MAP
from .quotation_quotation import QUOTATION_DATA_MAP
from .sale_data_contact import SALE_DATA_CONTACT_MAP
from .sale_data_account import SALE_DATA_ACCOUNT_MAP
from .saleorder_sale_order import SALE_ORDER_DATA_MAP
from .eoffice_leave_request import LEAVE_DATA_MAP
from .eoffice_business_trip import BUSINESS_TRIP_DATA_MAP
from .eoffice_asset_tools import *
from .distribution_plan_distributionplan import DISTRIBUTION_PLAN_DATA_MAP
from .contract_contract_approval import CONTRACT_APPROVAL_DATA_MAP
from .leaseorder_lease_order import LEASE_ORDER_DATA_MAP
from .financial_cashinflow import CASHINFLOW_DATA_MAP
from .reconciliation import RECON_DATA_MAP
from .asset_fixedasset import FIXED_ASSET_DATA_MAP, FIXED_ASSET_WRITEOFF_DATA_MAP
from .asset_instrumenttool import INSTRUMENT_TOOL_DATA_MAP, INSTRUMENT_TOOL_WRITEOFF_DATA_MAP
from .kms_document_approval import KMS_DOCUMENT_APPROVAL_DATA_MAP
from .kms_incoming_document import INCOMING_DOCUMENT_DATA_MAP
from .hrm import OVERTIME_REQUEST_DATA_MAP, PAYROLL_TEMPLATE_DATA_MAP
from .servicequotation_servicequotation import SERVICE_QUOTATION_DATA_MAP

__all__ = [
    'InputMappingProperties',
]


class InputMappingProperties:
    SALE_DATA_CONTACT = SALE_DATA_CONTACT_MAP
    SALE_DATA_ACCOUNT = SALE_DATA_ACCOUNT_MAP
    DELIVERY_ORDER_DELIVERY = DELIVERY_DATA_MAP
    QUOTATION_QUOTATION = QUOTATION_DATA_MAP
    SALE_ORDER_SALE_ORDER = SALE_ORDER_DATA_MAP
    PURCHASING_PURCHASE_ORDER = PURCHASE_ORDER_DATA_MAP
    INVENTORY_GOODS_RECEIPT = GOODS_RECEIPT_DATA_MAP
    PURCHASING_PURCHASE_REQUEST = PURCHASE_REQUEST_DATA_MAP
    LEAVE_DATA_MAP = LEAVE_DATA_MAP
    CASHOUTFLOW_ADVANCE = ADVANCE_DATA_MAP
    CASHOUTFLOW_PAYMENT = PAYMENT_DATA_MAP
    CASHOUTFLOW_RETURN_ADVANCE = RETURN_ADVANCE_DATA_MAP
    BUSINESS_TRIP_DATA_MAP = BUSINESS_TRIP_DATA_MAP
    ASSET_PROVIDE_DATA_MAP = ASSET_PROVIDE_DATA_MAP
    ASSET_DELIVERY_DATA_MAP = ASSET_DELIVERY_DATA_MAP
    ASSET_RETURN_DATA_MAP = ASSET_RETURN_DATA_MAP
    INVENTORY_GOODS_ISSUE = GOODS_ISSUE_DATA_MAP
    INVENTORY_GOODS_TRANSFER = GOODS_TRANSFER_DATA_MAP
    INVENTORY_GOODS_RETURN = GOODS_RETURN_DATA_MAP
    DISTRIBUTION_PLAN_DB = DISTRIBUTION_PLAN_DATA_MAP
    CONTRACT_APPROVAL_DATA_MAP = CONTRACT_APPROVAL_DATA_MAP
    BIDDING_DATA_MAP = BIDDING_DATA_MAP
    LEASE_ORDER_LEASE_ORDER = LEASE_ORDER_DATA_MAP
    CONSULTING_DATA_MAP = CONSULTING_DATA_MAP
    CASHINFLOW_DATA_MAP = CASHINFLOW_DATA_MAP
    RECON_DATA_MAP = RECON_DATA_MAP
    FIXED_ASSET_DATA_MAP = FIXED_ASSET_DATA_MAP
    INSTRUMENT_TOOL_DATA_MAP = INSTRUMENT_TOOL_DATA_MAP
    FIXED_ASSET_WRITEOFF_DATA_MAP = FIXED_ASSET_WRITEOFF_DATA_MAP
    INSTRUMENT_TOOL_WRITEOFF_DATA_MAP = INSTRUMENT_TOOL_WRITEOFF_DATA_MAP
    KMS_DOCUMENT_APPROVAL_DATA_MAP = KMS_DOCUMENT_APPROVAL_DATA_MAP
    INCOMING_DOCUMENT_DATA_MAP = INCOMING_DOCUMENT_DATA_MAP
    HRM_OVERTIME_REQUEST = OVERTIME_REQUEST_DATA_MAP
    HRM_PAYROLL_TEMPLATE = PAYROLL_TEMPLATE_DATA_MAP
    SERVICE_QUOTATION_DATA_MAP = SERVICE_QUOTATION_DATA_MAP